app:
  host: 0.0.0.0
  port: 8899
  logdir: ./log

llm:
  model_name: gpt-3.5-turbo
  temperature: 0.0
  max_input_size: 3900
  num_output: 256
  max_chunk_overlap: 40

  llama_index:
    persist_dir: ./llm_storage/llama_index
  langchain:
    persist_dir: ./llm_storage/langchain
    qa_chain_type: stuff # stuff, map_reduce, refine, map_rerank

db:
  host: ${env:DB_HOST}
  port: ${env:DB_PORT}
  username: ${env:DB_USERNAME}
  password: ${env:DB_PASSWORD}
  database: ${env:DB_NAME}
  direct_connection: ${env:DB_DIRECT_CONNECTION}
  server_selection_timeout_ms: ${env:DB_SERVER_SELECTION_TIMEOUT_MS}
  tls: ${env:DB_TLS}
  tls_insecure: ${env:DB_TLS_INSECURE}

smtp:
  server: ${env:SMTP_SERVER}
  port: ${env:SMTP_PORT}
  starttls: ${env:SMTP_START_TLS}
  ssl: ${env:SMTP_SSL}
  user: ${env:SMTP_USER}
  password: ${env:SMTP_PASSWORD}
  mail_from: ${env:SMTP_MAIL_FROM}
