llm:
  model_name: gpt-3.5-turbo-0301
  temperature: 0.2
  max_input_size: 3900
  num_output: 256
  max_chunk_overlap: 40
db:
  host: ${env:DB_HOST}
  port: ${env:DB_PORT}
  username: ${env:DB_USERNAME}
  password: ${env:DB_PASSWORD}
  database: ${env:DB_NAME}
  direct_connection: ${env:DB_DIRECT_CONNECTION}
  server_selection_timeout_ms: ${env:DB_SERVER_SELECTION_TIMEOUT_MS}
  tls: ${env:DB_TLS}
  tls_insecure: ${env:DB_TLS_INSECURE}
