name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: 52.221.42.209
        username: root
        key: ${{ secrets.SSH_KEY }}
        port: 22
        command_timeout: 60m
        script: |
          cd /root/chatgpt-automation-utils-api
          git checkout main
          git reset --hard HEAD
          git pull origin main
          docker build -t chatgpt-automation-utils-api:latest .
          systemctl restart chatgpt-automation-utils-api
          systemctl status chatgpt-automation-utils-api
